"use server";

import { randomUUID } from "node:crypto";
import { redirect } from "next/navigation";
import { createServerSupabase } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { sendEmail, isEmailConfigured } from "@/lib/email";
import { appBaseUrl } from "@/lib/app-url";
import { postAuthDest } from "@/lib/profile";
import type { LoginState, VerifyState } from "./login-state";

/** The sign-in email: the 6-digit code front and centre (entered in the code box,
 *  works in any browser), with a one-tap link fallback that verifies server-side
 *  (/auth/confirm), so it also works cross-browser. */
function codeEmailHtml(code: string, link: string): string {
  return `
<div style="font-family:system-ui,-apple-system,Segoe UI,sans-serif;max-width:480px;margin:0 auto">
  <h2 style="margin:0 0 8px">Your World Cup 2026 sign-in code</h2>
  <p style="font-size:15px;color:#444;margin:0 0 16px">
    Enter this code in the tab where you started signing in:
  </p>
  <p style="font-family:ui-monospace,Menlo,monospace;font-size:34px;font-weight:800;
            letter-spacing:10px;background:#f3f0fa;color:#1c1917;
            padding:16px 20px;border-radius:14px;text-align:center;
            margin:0 0 8px;user-select:all">${code}</p>
  <p style="font-size:13px;color:#777;margin:0 0 28px">
    Typing the code keeps you signed in <strong>in the browser you want to play in</strong>.
    The code expires shortly &mdash; request a new one if it does.
  </p>
  <hr style="border:none;border-top:1px solid #eee;margin:0 0 20px">
  <p style="font-size:13px;color:#777;margin:0 0 12px">
    Prefer to just tap? This link signs you in:
  </p>
  <p style="margin:0">
    <a href="${link}" style="display:inline-block;background:#0b8a3e;color:#fff;
              font-weight:700;font-size:15px;text-decoration:none;
              padding:12px 22px;border-radius:999px">Sign in &rarr;</a>
  </p>
</div>`.trim();
}

/** Minimum gap between sign-in codes for one address, so repeated "Resend" taps
 *  can't burn through the email provider's send limits. */
const CODE_COOLDOWN_MS = 2 * 60 * 1000;

/** A friendly wait, e.g. "47 seconds" or "1 min 12s". */
function formatWait(seconds: number): string {
  if (seconds < 60) return `${seconds} seconds`;
  const s = seconds % 60;
  return s ? `${Math.floor(seconds / 60)} min ${s}s` : `${Math.floor(seconds / 60)} min`;
}

/**
 * Send a 6-digit sign-in code, generated by us and delivered through our own
 * Resend pipeline (src/lib/email.ts) — not Supabase's auth mailer. We mint the
 * one-time code via the admin API (an existing address gets a "magiclink" code; a
 * brand-new one a "signup" code, which needs a throwaway password it never uses),
 * then email it ourselves. This sidesteps Supabase's dashboard email templates
 * entirely, so the code is guaranteed to be in the message.
 *
 * Resends for one address are throttled to CODE_COOLDOWN_MS apart — the email
 * provider's send limits are finite, so a user mashing "Resend" shouldn't spend
 * them. The throttle is keyed by email in login_code_requests (server-enforced,
 * so it holds across tabs and devices, not just this browser).
 */
export async function sendMagicLinkAction(
  _prev: LoginState,
  form: FormData,
): Promise<LoginState> {
  const email = String(form.get("email") ?? "")
    .trim()
    .toLowerCase();
  const next = String(form.get("next") ?? "/");
  if (!email || !email.includes("@")) {
    return { status: "error", error: "Enter a valid email address." };
  }
  if (!isEmailConfigured()) {
    return {
      status: "error",
      error: "Email isn't configured on the server yet. Please try again later.",
    };
  }

  const admin = createAdminClient();

  // Throttle: refuse a new code while the last one for this address is still
  // within the cooldown. Reads/writes go through the service role. (If the table
  // isn't there yet the read just returns nothing and we fall through — the
  // throttle fails open rather than locking anyone out.)
  const { data: last } = await admin
    .from("login_code_requests")
    .select("last_sent_at")
    .eq("email", email)
    .maybeSingle();
  if (last?.last_sent_at) {
    const remainingMs =
      CODE_COOLDOWN_MS - (Date.now() - Date.parse(last.last_sent_at as string));
    if (remainingMs > 0) {
      const seconds = Math.ceil(remainingMs / 1000);
      return {
        status: "sent",
        email,
        retryAfter: seconds,
        error: `You just requested a code — you can ask for another in ${formatWait(seconds)}.`,
      };
    }
  }

  // Existing user → magic-link code; if that fails (no such user yet), create
  // them with a signup code. The throwaway password is never used — sign-in is
  // always via the emailed code.
  let res = await admin.auth.admin.generateLink({ type: "magiclink", email });
  if (res.error || !res.data?.properties?.email_otp) {
    res = await admin.auth.admin.generateLink({
      type: "signup",
      email,
      password: randomUUID(),
    });
  }
  const props = res.data?.properties;
  if (res.error || !props?.email_otp) {
    return {
      status: "error",
      error: "Couldn't send your code — double-check the address and try again.",
    };
  }

  const appUrl = appBaseUrl();
  const link =
    `${appUrl}/auth/confirm?token_hash=${props.hashed_token}` +
    `&type=${props.verification_type}&next=${encodeURIComponent(next)}`;
  try {
    await sendEmail({
      to: email,
      subject: `Your World Cup 2026 sign-in code: ${props.email_otp}`,
      html: codeEmailHtml(props.email_otp, link),
    });
  } catch {
    return {
      status: "error",
      error: "Couldn't send your code right now — please try again in a moment.",
    };
  }

  // Record the send so the cooldown can throttle the next request for this email.
  await admin
    .from("login_code_requests")
    .upsert({ email, last_sent_at: new Date().toISOString() });

  return { status: "sent", email };
}

/**
 * Verify the 6-digit code from the magic-link email. Unlike clicking the link
 * (which opens — and signs you in on — the device's *default* browser, and whose
 * PKCE verifier only lives in the browser that requested it), entering the code
 * signs you in right here, in the same browser the user is already in. That's
 * the whole point: no cross-browser "stuck" state.
 */
export async function verifyEmailOtpAction(
  _prev: VerifyState,
  form: FormData,
): Promise<VerifyState> {
  const email = String(form.get("email") ?? "")
    .trim()
    .toLowerCase();
  const token = String(form.get("token") ?? "").replace(/\D/g, "");
  const next = String(form.get("next") ?? "/");
  // Supabase's email OTP length is a project setting (6–10 digits); accept the
  // whole range rather than hard-coding one length.
  if (token.length < 6 || token.length > 10) {
    return { status: "error", error: "Enter the code from your email." };
  }

  const supabase = await createServerSupabase();
  // A returning user's code is an "email" (magic-link) OTP; a brand-new user's
  // code is a "signup" confirmation OTP. We can't tell which from here, and the
  // 6-digit token is the same either way, so try the magic-link type first and
  // fall back to signup. Both verify the same token, so the fallback is safe.
  let { data, error } = await supabase.auth.verifyOtp({
    email,
    token,
    type: "email",
  });
  if (error || !data.user) {
    ({ data, error } = await supabase.auth.verifyOtp({
      email,
      token,
      type: "signup",
    }));
  }
  if (error || !data.user) {
    return {
      status: "error",
      error: "That code didn't work — double-check it, or request a new one.",
    };
  }

  const dest = await postAuthDest(data.user.id, next);
  redirect(dest);
}
